### ISSUE TITLE
Créer un évènement

### ISSUE THREAD

**Issue by johnSilver7** [BandStormTeam/BandStormProject#10]
En tant qu'utilsateur, 
Je souhaite créer un èvènement de type : 
- concert
- projet musical contenant une ou des chanson(s)
  Afin de permettre à d'autres utilsateurs de rejoindre ou de contribuer à mon projet

**Comment by steve-anthony** [comment]
Given: Après avoir cliqué sur le sous menu pour la création d’événement.
When: J'ai rempli le formulaire et j'appuie sur créer un événement.
Then: Mon événement apparaît sur mon fil d'actualité et celui de mes followers.
