### ISSUE TITLE
Création du service DAO pour status

### ISSUE THREAD

**Issue by Zac-Z88** [BandStormTeam/BandStormProject#12]
Création du service DAO pour la classe du domaine status

**Comment by johnSilver7** [comment]
Given : je suis sur la page d'accueil des inscrits 
When : je dispose d'un champ de texte où je peux entrer un statut, quand j'entre mon message et clique sur publier
Then : mon statut s'affiche sur mon fil d'actualité

**Comment by vlaks** [comment]
[] Contrôlleur pour status.
[] Créer un service DAO pour status.
[] Test service DAO.
[] Méthode d'ajout de status pour un utilisateur (User service)
[] Test méthode d'ajout
