### ISSUE TITLE
Editer son profil

### ISSUE THREAD

**Issue by vlaks** [BandStormTeam/BandStormProject#14]
### Description

En tant qu'utilisateur,
Je souhaite éditer les informations concernant mon profil
Afin de pouvoir le mettre à jour moi même.
### Test d’acceptation

_Given:_ Un utilisateur connecté au site.
_When:_ Je clique sur le bouton "paramètres".
_Then:_ J'arrive sur une nouvelle page me permettant de mettre à jour les différents éléments de mon profil.
### Tâches
- [x] Edition des données personnelles.
- [x] Edition du mot de passe.

**Comment by johnSilver7** [comment]
Given :  Je suis sur la page d'accueil inscrit 
When : Je clique sur le bouton paramètre
Then : J'arrive sur une nouvelle page me permettant de mettre à jour les différents éléments de mon profil

**Comment by steve-anthony** [comment]
Mergé
