### ISSUE TITLE
Identification

### ISSUE THREAD

**Issue by Zac-Z88** [BandStormTeam/BandStormProject#2]
### Description

En tant qu'utilisateur
Je souhaite me connecter
Afin de visualiser mes informations personnelles
### Test d'acceptance

_Given:_
Un utilisateur non connecté au site.
_When:_
Cet utilisateur indique son nom de compte et son mot de passe pour ce connecter.
_And:_
Les informations fournies sont valides.
_Then:_
L'utilisateur est redirigé vers la page principale du site.

Dépend de #25

**Comment by steve-anthony** [comment]
Erreurs d'intégration

**Comment by Zac-Z88** [comment]
Comment est ce qu'il peut y avoir une erreur d'intégration si je n'ai même pas commencé l'intégration.
Comme je l'ai déjà dis je ferais ça sur une branche à part.

**Comment by aroquemaurel** [comment]
Je t'ai expliqué par mail. 

Mais pour rappel ici, que tout le monde soit d'accord.

Il faut que la branche de sprint (0.1 en l'occurence) soit systématiquement fonctionnelle sur Github.
Dans le cas contraire, ça peut bloquer l'ensemble de l'équipe, et surtout c'est loin d'être safe… ;-)

Désolé ^_^
![](http://7-themes.com/data_images/out/75/7029313-cute-cat-sleeping-wallpaper.jpg)

**Comment by Zac-Z88** [comment]
ça marche :)
