### ISSUE TITLE
Recherche

### ISSUE THREAD

**Issue by Zac-Z88** [BandStormTeam/BandStormProject#5]
En tant que utilisateur
Je souhaite rechercher des utilisateurs ou des groupe.
Je trouve des groupes ou des utilisateurs en fonction de ma recherche.

**Comment by johnSilver7** [comment]
Given : Je suis sur la page de recherche.
When : je tape ma recherche et la valide 
Then : je suis redirigé vers une nouvelle page présentant les résultats de ma recherche et différentes catégories me permettant de la préciser : groupe ou utilisateur.
