### ISSUE TITLE
Suivre un utilisateur

### ISSUE THREAD

**Issue by Zac-Z88** [BandStormTeam/BandStormProject#8]
En tant que utilisateur
Je souhaite suivre un autre utilisateur
Afin d'être notifié des contributions de celui-ci

**Comment by steve-anthony** [comment]
Given: Je suis connecté.
When: J'appuis sur le bouton suivre un utilisateur.
Then: J'ai ajouté l'utilisateur aux personnes que je suis et je peux voir son actualité.
