### ISSUE TITLE
Lighter un élément

### ISSUE THREAD

**Issue by steve-anthony** [BandStormTeam/BandStormProject#9]
### Description

En tant qu'utilisateur inscrit,
Je souhaite disposer du moyen pour pouvoir aimer un commentaire, un statut, un événement, un groupe. Lighter  est le nom de cette fonctionnalité.
Afin de dialoguer avec les autres utilisateurs.
### Test d'acceptance

_Given:_
Un utilisateur qui souhaite "lighter" (aimer) une publication, un événement ou groupe.
_When:_
L'utilisateur clique sur le bouton "I light".
_Then:_
Son "light" est ajouter et pris en compte dans le compte des "lights" pour cet élément.

**Comment by johnSilver7** [comment]
Given : je suis sur la page d'accueil des inscrits. Les évènements, groupes, status etc disposent d'un petit bouton "briquet". 
When :  Quand je clique sur un briquet
Then : Le compte de "lights" de l'évènement ou groupe est incrémenté et il est ajouté à ma liste d'évènement, light etc.
